{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "witchcult.shop.serviceAccountName" . }}
  labels:
{{ include "witchcult.shop.labels" . | nindent 4 }}
{{- end -}}
