version: '3.5'
services:
  web:
    build: '.'
    volumes:
      - .:/data
    working_dir: /data
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    ports:
     - '9000:9000'
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'
