on:
  push:
    branches:
      - main
  pull_request:

name: ci
description: 'Run CI.'

jobs:
  RSpec:
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up -d
